### ISSUE TITLE
Inhalte nicht einsehbar

### ISSUE THREAD

**Issue by pungar** [TeachAtTUM/edx-platform#13]
Hallo ihr Lieben,

wenn man bei Edx oben unter View as "Student" auswählt, kann man noch keine Inhalte (außer den Einführungsseiten) sehen. Wisst ihr wahrscheinlich schon, aber damit es hier auch vermerkt ist.
Und bei dem persönlichen Code steht "Drücken Sie auf Speichern" und unten steht auf dem Button "Save". Vielleicht könnten wir das angleichen? Und wenn man dann auf "Save" klickt, passiert nichts, also es kommt keine Bestätigung o. Ä.
Viele Grüße und DANKE!

**Comment by jvw123** [comment]
Huhu Patrizia :)
Das mit der Sichtbarkeit ist eine Sache, die wir einfach ein- und ausstellen. Hat mit der Technik nichts zu tun. Momentan sind unsere Kurse noch unsichtbar. Lässt sich aber mit einem Klick umstellen!

**Comment by pungar** [comment]
Ah klasse, vielen Dank Jana! Dann weiß ich Bescheid :-)

**Comment by MirjamMaahs** [comment]
beides erledigt.

**Comment by pungar** [comment]
Vielen Dank!
