### ISSUE TITLE
Module nicht mehr sichtbar bei Anmeldung Testuser

### ISSUE THREAD

**Issue by MirjamMaahs** [TeachAtTUM/edx-platform#14]
Melde ich mich als Testuser an sehe ich inzwischen nicht mehr die Module, sondern diese Ansicht (auch bei Klick auf Link hinter "School of Edu..." tut sich nichts):

<img width="1200" alt="bildschirmfoto 2017-05-15 um 11 40 57" src="https://cloud.githubusercontent.com/assets/16760062/26051746/67cd64cc-3963-11e7-97ed-79e9ddff1acc.png">

Vorher:
<img width="1114" alt="bildschirmfoto 2017-05-15 um 11 42 55" src="https://cloud.githubusercontent.com/assets/16760062/26051841/be3b37bc-3963-11e7-8a08-55fc00ea3159.png">

Woran liegts? Sollten wir wieder umstellen.

**Comment by Ivorforce** [comment]
Das obere ist das Studio, das untere das LMS. Du bist einfach auf der falschen website (i.e. nimm das :18010 vom Link weg).

**Comment by MirjamMaahs** [comment]
Das kann ich den Studenten ja nicht laufend sagen. 
Wenn man sich einloggt, leitet es auf 18010 weiter, hier sollte auf http://tuedfvw-openedx.srv.mwn.de verlinkt werden.

**Comment by Ivorforce** [comment]
Dann ist der link von der startpage falsch gesetzt. Wenn man sich auf tuedfvw-openedx einloggt funktioniert es einwandfrei.

**Comment by MirjamMaahs** [comment]
ok danke. habs angepasst
