### ISSUE TITLE
Textfeld speichern

### ISSUE THREAD

**Issue by MirjamMaahs** [TeachAtTUM/edx-platform#17]
im 18010 funktioniert's:
<img width="819" alt="bildschirmfoto 2017-05-16 um 11 59 27" src="https://cloud.githubusercontent.com/assets/16760062/26100832/50420fca-3a2f-11e7-98ab-20d9dc1fea2f.png">
in der Liveversion speichert er nicht.

**Comment by Ivorforce** [comment]
Fertig - die mathjax CDN wurde heruntergefahren, das musste ich per Hand nachbessern.
