### ISSUE TITLE
Error in Dropdown Aufgabe

### ISSUE THREAD

**Issue by jvw123** [TeachAtTUM/edx-platform#3]
In B&A Aufgaben:Grundlagen funktioniert eine Dropdown Aufgabe (Aufgabe 2) nicht. Alle anderen Dropdowns funktionieren in meinem Modul. 
![grafik](https://cloud.githubusercontent.com/assets/28561689/25848634/85cf75f2-34bb-11e7-82be-d28fc7907130.png)

**Comment by Ivorforce** [comment]
Scheinbar darf man keine Anführungszeichen verwenden. Zur Referenz:

    <option correct="False">"Gut gemacht. Weiter geht's. <optionhint>Kein Eingehen auf das Argument.</optionhint></option>

wird zu

    <option correct="False">Gut gemacht. Weiter geht's. <optionhint>Kein Eingehen auf das Argument.</optionhint></option>

und das hat das Problem gelöst.

Ich hab das mal selbst korrigiert - frag mich nicht warum das so muss, ich hätt's auch nicht gewusst.
