### ISSUE TITLE
Error in Checkboxes Aufgabe

### ISSUE THREAD

**Issue by jvw123** [TeachAtTUM/edx-platform#4]
In B&A Aufgaben: Lernziel 2 funktioniert eine Checkboxes Aufgabe (Aufgabe 6) nicht. Alle anderen Checkboxes funktionieren in meinem Modul.
![grafik](https://cloud.githubusercontent.com/assets/28561689/25848705/d2fefe74-34bb-11e7-9e77-21b2d6916084.png)

**Comment by Ivorforce** [comment]
Sollte jetzt funktionieren.

**Comment by jvw123** [comment]
supi :)
Falls es ein Fehler von meiner Seite der Programmierung/Aufgabenerstellung her war, kannst du mir das gerne versuchen zu erklären, damit er nicht wieder vorkommt. Gilt auch generell für alles, was ich hier so reinstelle!

**Comment by Ivorforce** [comment]
Nein, ich musste hier nur einmal die caches leeren :)
