### ISSUE TITLE
Live Version Modul 2

### ISSUE THREAD

**Issue by jvw123** [TeachAtTUM/edx-platform#7]
Wenn ich Modul 2 in der Live Version anschauen möchte, bekomme ich diesen Fehler gezeigt:
![grafik](https://cloud.githubusercontent.com/assets/28561689/25849269/119344a4-34be-11e7-9991-a2f494ae1fe6.png)
Miri kann die Live Version problemlos öffnen.

**Comment by jvw123** [comment]
gerade getestet: Modul 1 und 3 lassen sich beide Live anschauen

**Comment by jvw123** [comment]
gerade getestet: es funktionieren alle Seiten bis auf die Aufgaben

**Comment by Ivorforce** [comment]
Ist es ok wenn du gerade nichts an Modul 2 machst? Ich kann den Fehler beheben aber brauche den Kurs für 5 Minuten unbearbeitet.

**Comment by jvw123** [comment]
Ist kein Problem. Schick das nur auch an Maria&Miri, falls die auch gerade dran sind.

**Comment by Ivorforce** [comment]
@MirjamMaahs, @MaRei123

**Comment by jvw123** [comment]
Ah, so geht das hier :)

**Comment by MaRei123** [comment]
Passt, ich lass die Finger weg bis du das Modul wieder frei gibst.

**Comment by Ivorforce** [comment]
Sollte behoben sein, Arbeit ist wieder freigegeben.
